
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author IsmaelYoussef
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester; 
    
    public MainFrame() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
    }
    
    public void rebuildSemesterComboBoxes()
    {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));

        if (semesters.size() > 0)
        {
            currentSemesterLabel.setText((String)currentSemesterComboBox.getSelectedItem());
            currentSemester = (String)currentSemesterComboBox.getSelectedItem();
        }
        else
        {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    
    public void rebuildCourseComboBoxes(){
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        SelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DropCourseComboBox_DropCourse_Admin.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        SelectCourseComboBox_DisplayCourseListofStudents.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        SelectCourseDropCourse_StudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
    }
    
    public void rebuildStudentComboBoxes(){
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();

        StudentNameComboBox_DisplaySchedule.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        StudentNameComboBox_ScheduleCourse.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        StudentNameComboBox_DropCourse_Student.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        SelectStudentComboBox_DropStudent.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Header = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AdminPanel = new javax.swing.JPanel();
        AdminTab = new javax.swing.JTabbedPane();
        Admin_AddSemesterPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        Admin_AddCoursePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CourseNameTextField_AddCourse = new javax.swing.JTextField();
        AddCourseSubmitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CourseDescriptionTextField_AddCourse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SeatsSpinner_AddCourse = new javax.swing.JSpinner();
        AddCourseOutputLabel = new javax.swing.JLabel();
        Admin_AddStudentPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        StudentIDTextField_AddStudent = new javax.swing.JTextField();
        AddStudentSubmitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        FirstNameTextField_AddStudent = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LastNameTextField_AddStudent = new javax.swing.JTextField();
        AddStudentOutputLabel = new javax.swing.JLabel();
        Admin_DisplayCourseListofStudentPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SelectCourseComboBox_DisplayCourseListofStudents = new javax.swing.JComboBox<>();
        DisplayButton_DisplayCourseListofStudents = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents = new javax.swing.JTable();
        Admin_DropStudentPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        SelectStudentComboBox_DropStudent = new javax.swing.JComboBox<>();
        DropStudentButton_DropStudent = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        DropStudentOutputTextArea = new javax.swing.JTextArea();
        Admin_DropCoursePanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        DropCourseComboBox_DropCourse_Admin = new javax.swing.JComboBox<>();
        DropCourseButton_DropCourse_Admin = new javax.swing.JButton();
        DropCourse_AdminOutputPanel = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        StudentTab = new javax.swing.JTabbedPane();
        Student_DisplaySchedulePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayScheduleTable = new javax.swing.JTable();
        DisplayButton_DisplaySchedule = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        StudentNameComboBox_DisplaySchedule = new javax.swing.JComboBox<>();
        Student_DisplayCoursesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayCoursesTable = new javax.swing.JTable();
        DisplayButton_DisplayCourses = new javax.swing.JButton();
        Student_ScheduleCoursePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        SelectCourseComboBox = new javax.swing.JComboBox<>();
        ScheduleCourseSubmitButton = new javax.swing.JButton();
        ScheduleCourseOutput = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StudentNameComboBox_ScheduleCourse = new javax.swing.JComboBox<>();
        Student_DropCoursePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SelectCourseDropCourse_StudentComboBox = new javax.swing.JComboBox<>();
        DropCourse_StudentSubmitButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        StudentNameComboBox_DropCourse_Student = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        DropCourseOutputTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        Header.setForeground(new java.awt.Color(0, 153, 153));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Course Scheduler");

        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout Admin_AddSemesterPanelLayout = new javax.swing.GroupLayout(Admin_AddSemesterPanel);
        Admin_AddSemesterPanel.setLayout(Admin_AddSemesterPanelLayout);
        Admin_AddSemesterPanelLayout.setHorizontalGroup(
            Admin_AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddSemesterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Admin_AddSemesterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addSemesterSubmitButton))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        Admin_AddSemesterPanelLayout.setVerticalGroup(
            Admin_AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddSemesterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSemesterSubmitButton)
                .addGap(24, 24, 24)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        AdminTab.addTab("Add Semester", Admin_AddSemesterPanel);

        jLabel1.setText("Course Name:");

        CourseNameTextField_AddCourse.setColumns(20);
        CourseNameTextField_AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseNameTextField_AddCourseActionPerformed(evt);
            }
        });

        AddCourseSubmitButton.setText("Submit");
        AddCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseSubmitButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Course Description:");

        jLabel6.setText("Seats:");

        javax.swing.GroupLayout Admin_AddCoursePanelLayout = new javax.swing.GroupLayout(Admin_AddCoursePanel);
        Admin_AddCoursePanel.setLayout(Admin_AddCoursePanelLayout);
        Admin_AddCoursePanelLayout.setHorizontalGroup(
            Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Admin_AddCoursePanelLayout.createSequentialGroup()
                        .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CourseNameTextField_AddCourse)
                            .addComponent(CourseDescriptionTextField_AddCourse)
                            .addComponent(SeatsSpinner_AddCourse)))
                    .addComponent(AddCourseSubmitButton)
                    .addComponent(AddCourseOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        Admin_AddCoursePanelLayout.setVerticalGroup(
            Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CourseNameTextField_AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CourseDescriptionTextField_AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Admin_AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(SeatsSpinner_AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddCourseSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCourseOutputLabel)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        AdminTab.addTab("Add Course", Admin_AddCoursePanel);

        jLabel4.setText("Student ID:");

        StudentIDTextField_AddStudent.setColumns(20);
        StudentIDTextField_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextField_AddStudentActionPerformed(evt);
            }
        });

        AddStudentSubmitButton.setText("Submit");
        AddStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentSubmitButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("First Name: ");

        FirstNameTextField_AddStudent.setColumns(20);
        FirstNameTextField_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextField_AddStudentActionPerformed(evt);
            }
        });

        jLabel8.setText("Last Name: ");

        LastNameTextField_AddStudent.setColumns(20);
        LastNameTextField_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextField_AddStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Admin_AddStudentPanelLayout = new javax.swing.GroupLayout(Admin_AddStudentPanel);
        Admin_AddStudentPanel.setLayout(Admin_AddStudentPanelLayout);
        Admin_AddStudentPanelLayout.setHorizontalGroup(
            Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin_AddStudentPanelLayout.createSequentialGroup()
                        .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(Admin_AddStudentPanelLayout.createSequentialGroup()
                                .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddStudentSubmitButton)
                                    .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameTextField_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentIDTextField_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameTextField_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(376, 376, 376))
                    .addGroup(Admin_AddStudentPanelLayout.createSequentialGroup()
                        .addComponent(AddStudentOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        Admin_AddStudentPanelLayout.setVerticalGroup(
            Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_AddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDTextField_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FirstNameTextField_AddStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Admin_AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddStudentSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddStudentOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        AdminTab.addTab("Add Student", Admin_AddStudentPanel);

        jLabel14.setText("Select Course: ");

        SelectCourseComboBox_DisplayCourseListofStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DisplayButton_DisplayCourseListofStudents.setText("Display");
        DisplayButton_DisplayCourseListofStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButton_DisplayCourseListofStudentsActionPerformed(evt);
            }
        });

        jLabel15.setText("Scheduled Students");

        ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "Student ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents);
        if (ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumnCount() > 0) {
            ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(0).setResizable(false);
            ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(1).setResizable(false);
            ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel16.setText("Waitlisted Students");

        WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "Student ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents);
        if (WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumnCount() > 0) {
            WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(0).setResizable(false);
            WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(1).setResizable(false);
            WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout Admin_DisplayCourseListofStudentPanelLayout = new javax.swing.GroupLayout(Admin_DisplayCourseListofStudentPanel);
        Admin_DisplayCourseListofStudentPanel.setLayout(Admin_DisplayCourseListofStudentPanelLayout);
        Admin_DisplayCourseListofStudentPanelLayout.setHorizontalGroup(
            Admin_DisplayCourseListofStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createSequentialGroup()
                        .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SelectCourseComboBox_DisplayCourseListofStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisplayButton_DisplayCourseListofStudents))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        Admin_DisplayCourseListofStudentPanelLayout.setVerticalGroup(
            Admin_DisplayCourseListofStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DisplayCourseListofStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SelectCourseComboBox_DisplayCourseListofStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayButton_DisplayCourseListofStudents))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        AdminTab.addTab("Display Course List of Students", Admin_DisplayCourseListofStudentPanel);

        jLabel17.setText("Select Student:");

        SelectStudentComboBox_DropStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropStudentButton_DropStudent.setText("Drop Student");
        DropStudentButton_DropStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropStudentButton_DropStudentActionPerformed(evt);
            }
        });

        DropStudentOutputTextArea.setColumns(20);
        DropStudentOutputTextArea.setRows(5);
        jScrollPane8.setViewportView(DropStudentOutputTextArea);

        javax.swing.GroupLayout Admin_DropStudentPanelLayout = new javax.swing.GroupLayout(Admin_DropStudentPanel);
        Admin_DropStudentPanel.setLayout(Admin_DropStudentPanelLayout);
        Admin_DropStudentPanelLayout.setHorizontalGroup(
            Admin_DropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DropStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane8)
                    .addGroup(Admin_DropStudentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelectStudentComboBox_DropStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DropStudentButton_DropStudent)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        Admin_DropStudentPanelLayout.setVerticalGroup(
            Admin_DropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DropStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(SelectStudentComboBox_DropStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropStudentButton_DropStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        AdminTab.addTab("Drop Student", Admin_DropStudentPanel);

        jLabel18.setText("Select Course to be Droppped:");

        DropCourseComboBox_DropCourse_Admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropCourseButton_DropCourse_Admin.setText("Drop Course");
        DropCourseButton_DropCourse_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseButton_DropCourse_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Admin_DropCoursePanelLayout = new javax.swing.GroupLayout(Admin_DropCoursePanel);
        Admin_DropCoursePanel.setLayout(Admin_DropCoursePanelLayout);
        Admin_DropCoursePanelLayout.setHorizontalGroup(
            Admin_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin_DropCoursePanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DropCourseComboBox_DropCourse_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DropCourseButton_DropCourse_Admin))
                    .addComponent(DropCourse_AdminOutputPanel))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        Admin_DropCoursePanelLayout.setVerticalGroup(
            Admin_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin_DropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(DropCourseComboBox_DropCourse_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropCourseButton_DropCourse_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropCourse_AdminOutputPanel)
                .addGap(347, 347, 347))
        );

        AdminTab.addTab("Drop Course", Admin_DropCoursePanel);

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminTab)
                .addContainerGap())
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Admin", AdminPanel);

        DisplayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ));
        jScrollPane2.setViewportView(DisplayScheduleTable);

        DisplayButton_DisplaySchedule.setText("Display");
        DisplayButton_DisplaySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButton_DisplayScheduleActionPerformed(evt);
            }
        });

        jLabel11.setText("Student Name:");

        StudentNameComboBox_DisplaySchedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout Student_DisplaySchedulePanelLayout = new javax.swing.GroupLayout(Student_DisplaySchedulePanel);
        Student_DisplaySchedulePanel.setLayout(Student_DisplaySchedulePanelLayout);
        Student_DisplaySchedulePanelLayout.setHorizontalGroup(
            Student_DisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_DisplaySchedulePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisplayButton_DisplaySchedule)
                .addGap(337, 337, 337))
            .addGroup(Student_DisplaySchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_DisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(Student_DisplaySchedulePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StudentNameComboBox_DisplaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Student_DisplaySchedulePanelLayout.setVerticalGroup(
            Student_DisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DisplaySchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_DisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(StudentNameComboBox_DisplaySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayButton_DisplaySchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentTab.addTab("Display Schedule", Student_DisplaySchedulePanel);

        DisplayCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ));
        DisplayCoursesTable.setAutoscrolls(false);
        DisplayCoursesTable.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(DisplayCoursesTable);
        DisplayCoursesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        DisplayButton_DisplayCourses.setText("Display");
        DisplayButton_DisplayCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButton_DisplayCoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_DisplayCoursesPanelLayout = new javax.swing.GroupLayout(Student_DisplayCoursesPanel);
        Student_DisplayCoursesPanel.setLayout(Student_DisplayCoursesPanelLayout);
        Student_DisplayCoursesPanelLayout.setHorizontalGroup(
            Student_DisplayCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DisplayCoursesPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_DisplayCoursesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisplayButton_DisplayCourses)
                .addGap(340, 340, 340))
        );
        Student_DisplayCoursesPanelLayout.setVerticalGroup(
            Student_DisplayCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DisplayCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayButton_DisplayCourses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentTab.addTab("Display Courses", Student_DisplayCoursesPanel);

        jLabel9.setText("Select Course:");

        SelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ScheduleCourseSubmitButton.setText("Submit");
        ScheduleCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleCourseSubmitButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Student Name:");

        StudentNameComboBox_ScheduleCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout Student_ScheduleCoursePanelLayout = new javax.swing.GroupLayout(Student_ScheduleCoursePanel);
        Student_ScheduleCoursePanel.setLayout(Student_ScheduleCoursePanelLayout);
        Student_ScheduleCoursePanelLayout.setHorizontalGroup(
            Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_ScheduleCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScheduleCourseSubmitButton)
                    .addComponent(ScheduleCourseOutput)
                    .addGroup(Student_ScheduleCoursePanelLayout.createSequentialGroup()
                        .addGroup(Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentNameComboBox_ScheduleCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Student_ScheduleCoursePanelLayout.setVerticalGroup(
            Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_ScheduleCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Student_ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(StudentNameComboBox_ScheduleCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleCourseOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScheduleCourseSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StudentTab.addTab("Schedule Course", Student_ScheduleCoursePanel);

        jLabel12.setText("Select Course:");

        SelectCourseDropCourse_StudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropCourse_StudentSubmitButton.setText("Submit");
        DropCourse_StudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourse_StudentSubmitButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Student Name:");

        StudentNameComboBox_DropCourse_Student.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropCourseOutputTextArea.setColumns(20);
        DropCourseOutputTextArea.setRows(5);
        jScrollPane9.setViewportView(DropCourseOutputTextArea);

        javax.swing.GroupLayout Student_DropCoursePanelLayout = new javax.swing.GroupLayout(Student_DropCoursePanel);
        Student_DropCoursePanel.setLayout(Student_DropCoursePanelLayout);
        Student_DropCoursePanelLayout.setHorizontalGroup(
            Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DropCourse_StudentSubmitButton)
                    .addGroup(Student_DropCoursePanelLayout.createSequentialGroup()
                        .addGroup(Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectCourseDropCourse_StudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentNameComboBox_DropCourse_Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        Student_DropCoursePanelLayout.setVerticalGroup(
            Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_DropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectCourseDropCourse_StudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Student_DropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(StudentNameComboBox_DropCourse_Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropCourse_StudentSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        StudentTab.addTab("Drop Course", Student_DropCoursePanel);

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addComponent(StudentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addComponent(StudentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", StudentPanel);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(changeSemesterButton)
                                .addGap(80, 80, 80)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        String semester = addSemesterTextfield.getText();
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void CourseNameTextField_AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseNameTextField_AddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseNameTextField_AddCourseActionPerformed

    private void AddCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseSubmitButtonActionPerformed
        // TODO add your handling code here:
        if (CourseNameTextField_AddCourse.getText().length() > 0 && CourseDescriptionTextField_AddCourse.getText().length() > 0){
            CourseEntry newCourse = new CourseEntry(currentSemester, CourseNameTextField_AddCourse.getText(), CourseDescriptionTextField_AddCourse.getText(), (int)SeatsSpinner_AddCourse.getValue());
            CourseQueries.addCourse(newCourse);
            AddCourseOutputLabel.setText(CourseNameTextField_AddCourse.getText() + " has been added.");
            rebuildCourseComboBoxes();
        }
    }//GEN-LAST:event_AddCourseSubmitButtonActionPerformed

    private void StudentIDTextField_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextField_AddStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTextField_AddStudentActionPerformed

    private void FirstNameTextField_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextField_AddStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextField_AddStudentActionPerformed

    private void LastNameTextField_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextField_AddStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextField_AddStudentActionPerformed

    private void AddStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        if(StudentIDTextField_AddStudent.getText().length() > 0 && FirstNameTextField_AddStudent.getText().length() > 0 && LastNameTextField_AddStudent.getText().length() > 0){
            StudentEntry newStudent = new StudentEntry(StudentIDTextField_AddStudent.getText(), FirstNameTextField_AddStudent.getText(), LastNameTextField_AddStudent.getText());
            StudentQueries.addStudent(newStudent);
            AddStudentOutputLabel.setText(LastNameTextField_AddStudent.getText() + ", " + FirstNameTextField_AddStudent.getText() + " has been added.");
            rebuildStudentComboBoxes();
        }
    }//GEN-LAST:event_AddStudentSubmitButtonActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        // TODO add your handling code here:
        currentSemester = (String)currentSemesterComboBox.getSelectedItem();
        currentSemesterLabel.setText(currentSemester);
        rebuildCourseComboBoxes();

    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void DropCourse_StudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourse_StudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        DropCourseOutputTextArea.setText("");
        
        ScheduleQueries.dropStudentScheduleByCourse(currentSemester, ((StudentEntry)StudentNameComboBox_DropCourse_Student.getSelectedItem()).getStudentID(), ((CourseEntry)SelectCourseDropCourse_StudentComboBox.getSelectedItem()).getCourseCode());
        
        DropCourseOutputTextArea.append(((StudentEntry)StudentNameComboBox_DropCourse_Student.getSelectedItem()).getOutputString() + " has been dropped from " + ((CourseEntry)SelectCourseDropCourse_StudentComboBox.getSelectedItem()).getCourseCode() + "\n");
        
        ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, ((CourseEntry)SelectCourseDropCourse_StudentComboBox.getSelectedItem()).getCourseCode());
        if(waitlistedStudents.size() >= 1){
            ScheduleQueries.updateScheduleEntry(currentSemester, waitlistedStudents.get(0));
            DropStudentOutputTextArea.append(StudentQueries.getStudent(waitlistedStudents.get(0).getStudentID()).getOutputString() + "has been scheduled into " + ((CourseEntry)SelectCourseDropCourse_StudentComboBox.getSelectedItem()).getCourseCode() + "\n");       
        }
        
        rebuildStudentComboBoxes();
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_DropCourse_StudentSubmitButtonActionPerformed

    private void ScheduleCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleCourseSubmitButtonActionPerformed
        // TODO add your handling code here:
        String courseStatus = "";
        StudentEntry studentScheduled = (StudentEntry)StudentNameComboBox_ScheduleCourse.getSelectedItem();
        CourseEntry courseScheduled = (CourseEntry) SelectCourseComboBox.getSelectedItem();
        if(CourseQueries.getCourseSeats(currentSemester, courseScheduled.getCourseCode()) > ScheduleQueries.getScheduledStudentCount(currentSemester, courseScheduled.getCourseCode(), "S")){
            courseStatus = "S";
            ScheduleCourseOutput.setText(studentScheduled.getOutputString() + " has been scheduled for " + courseScheduled.getCourseCode());
        }
        else{
            courseStatus = "W";
            ScheduleCourseOutput.setText(studentScheduled.getOutputString() + " has been waitlisted for " + courseScheduled.getCourseCode());
        }
        ScheduleEntry newClass = new ScheduleEntry(currentSemester, (String)courseScheduled.getCourseCode(),(String) studentScheduled.getStudentID(), courseStatus, new java.sql.Timestamp(System.currentTimeMillis()));
        ScheduleQueries.addScheduleEntry(newClass);
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_ScheduleCourseSubmitButtonActionPerformed

    private void DisplayButton_DisplayCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButton_DisplayCoursesActionPerformed
        // TODO add your handling code here:
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        DefaultTableModel currentModel = (DefaultTableModel)DisplayCoursesTable.getModel();
        //resets table from last run
        currentModel.setNumRows(0);
        String[] rowData = new String[3];
        for(CourseEntry course: courses){
            rowData[0] = course.getCourseCode();
            rowData[1] = course.getDescription();
            rowData[2] = String.valueOf(course.getSeats());
            currentModel.addRow(rowData);
        }
    }//GEN-LAST:event_DisplayButton_DisplayCoursesActionPerformed

    private void DisplayButton_DisplayScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButton_DisplayScheduleActionPerformed
        // TODO add your handling code here:
        StudentEntry student = (StudentEntry)StudentNameComboBox_DisplaySchedule.getSelectedItem();
        ArrayList<ScheduleEntry> schedules = ScheduleQueries.getScheduleByStudent(currentSemester, student.getStudentID());
        DefaultTableModel currentModel = (DefaultTableModel) DisplayScheduleTable.getModel();
        currentModel.setNumRows(0);
        String[] rowData = new String[2];
        for (ScheduleEntry schedule : schedules){
            rowData[0] = (String)schedule.getCourseCode();
            if(schedule.getStatus().equals("W")){
                rowData[1] = "Waitlisted";
            }
            else if(schedule.getStatus().equals("S")){
                rowData[1] = "Scheduled";
            }
            System.out.println((String)schedule.getStatus());
            currentModel.addRow(rowData);
        }
    }//GEN-LAST:event_DisplayButton_DisplayScheduleActionPerformed

    private void DropCourseButton_DropCourse_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseButton_DropCourse_AdminActionPerformed
        // TODO add your handling code here:
        DropCourse_AdminOutputPanel.setText("");
        
        // setup the output field text by adding onto a base string all the students that were dropped
        String droppedScheduledStudentsMessage = "Scheduled students dropped from the course:\n";
        String droppedWaitlistedStudentsMessage = "Waitlisted students dropped from the course:\n";

        StudentEntry currentStudent;
        for (ScheduleEntry currentEntry : ScheduleQueries.getScheduledStudentsByCourse(currentSemester,((CourseEntry)DropCourseComboBox_DropCourse_Admin.getSelectedItem()).getCourseCode())){
            currentStudent = StudentQueries.getStudent(currentEntry.getStudentID());
            droppedScheduledStudentsMessage += currentStudent.getOutputString() + "\n";
        }
        for (ScheduleEntry currentEntry : ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, (String)DropCourseComboBox_DropCourse_Admin.getSelectedItem())){
            currentStudent = StudentQueries.getStudent(currentEntry.getStudentID());
            droppedWaitlistedStudentsMessage += currentStudent.getOutputString() + "\n";
        }
        
        ScheduleQueries.dropScheduleByCourse(currentSemester, (String) DropCourseComboBox_DropCourse_Admin.getSelectedItem());
        CourseQueries.dropCourse(currentSemester, (String) DropCourseComboBox_DropCourse_Admin.getSelectedItem());
        
        DropCourse_AdminOutputPanel.setText(droppedScheduledStudentsMessage + "\n" + droppedWaitlistedStudentsMessage);
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_DropCourseButton_DropCourse_AdminActionPerformed

    private void DropStudentButton_DropStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropStudentButton_DropStudentActionPerformed
        // TODO add your handling code here:
        DropStudentOutputTextArea.setText("");
        
        StudentEntry currentStudent = StudentQueries.getStudent(((StudentEntry)StudentNameComboBox_DropCourse_Student.getSelectedItem()).getStudentID());
        DropStudentOutputTextArea.append(((StudentEntry)StudentNameComboBox_DropCourse_Student.getSelectedItem()).getOutputString() + " has been dropped from the list of students.\n");

        
        for (String currentSem : SemesterQueries.getSemesterList()){
            
            String studentDroppedCourses = "";
            String WaitlistedStudentScheduled = "";
            
            for(ScheduleEntry currentSchedule : ScheduleQueries.getScheduleByStudent(currentSem, currentStudent.getStudentID())){
                ScheduleQueries.dropStudentScheduleByCourse(currentSem, currentStudent.getStudentID(), currentSchedule.getCourseCode());
                if(currentSchedule.getStatus().toLowerCase().equals("w")){
                    studentDroppedCourses += ((StudentEntry)SelectStudentComboBox_DropStudent.getSelectedItem()).getOutputString() + " has been dropped from the waitlist for " + currentSchedule.getCourseCode() + "\n";
                }
                else{
                    studentDroppedCourses += ((StudentEntry)SelectStudentComboBox_DropStudent.getSelectedItem()).getOutputString() + " has been dropped from " + currentSchedule.getCourseCode() + "\n";
                    ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currentSem, currentSchedule.getCourseCode());

                    if(waitlistedStudents.size() >= 1){
                        ScheduleQueries.updateScheduleEntry(currentSem, waitlistedStudents.get(0));
                        StudentEntry unwaitlistedStudent = StudentQueries.getStudent(waitlistedStudents.get(0).getStudentID());
                        WaitlistedStudentScheduled += unwaitlistedStudent.getOutputString() + " has been scheduled into " + waitlistedStudents.get(0).getCourseCode() + "\n";
                    }
                }
                if (!studentDroppedCourses.isEmpty() || !WaitlistedStudentScheduled.isEmpty()){
                    DropStudentOutputTextArea.append("For Semester: " + currentSem + "\n");
                    DropStudentOutputTextArea.append(studentDroppedCourses);
                    DropStudentOutputTextArea.append(WaitlistedStudentScheduled);
                }
            }
        }
        
        StudentQueries.dropStudent(((StudentEntry)SelectStudentComboBox_DropStudent.getSelectedItem()).getStudentID());
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_DropStudentButton_DropStudentActionPerformed

    private void DisplayButton_DisplayCourseListofStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButton_DisplayCourseListofStudentsActionPerformed
        // TODO add your handling code here:
        
        ArrayList<ScheduleEntry> scheduledStudents = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, ((CourseEntry)SelectCourseComboBox_DisplayCourseListofStudents.getSelectedItem()).getCourseCode());
        ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, ((CourseEntry)SelectCourseComboBox_DisplayCourseListofStudents.getSelectedItem()).getCourseCode());
        
        DefaultTableModel currentTableModel = (DefaultTableModel)ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents.getModel();
        currentTableModel.setNumRows(0);
        Object[] rowData = new Object[3];
        for(ScheduleEntry entry : scheduledStudents){
            StudentEntry currentStudent = StudentQueries.getStudent(entry.getStudentID());
            rowData[0] = currentStudent.getLastName();
            rowData[1] = currentStudent.getFirstName();
            rowData[2] = currentStudent.getStudentID();
            currentTableModel.addRow(rowData);
        }
        
        currentTableModel = (DefaultTableModel)WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents.getModel();
        currentTableModel.setNumRows(0);
        rowData = new Object[3];
        for(ScheduleEntry entry : waitlistedStudents){
            StudentEntry currentStudent = StudentQueries.getStudent(entry.getStudentID());
            rowData[0] = currentStudent.getLastName();
            rowData[1] = currentStudent.getFirstName();
            rowData[2] = currentStudent.getStudentID();
            currentTableModel.addRow(rowData);
        }
    }//GEN-LAST:event_DisplayButton_DisplayCourseListofStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCourseOutputLabel;
    private javax.swing.JButton AddCourseSubmitButton;
    private javax.swing.JLabel AddStudentOutputLabel;
    private javax.swing.JButton AddStudentSubmitButton;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JTabbedPane AdminTab;
    private javax.swing.JPanel Admin_AddCoursePanel;
    private javax.swing.JPanel Admin_AddSemesterPanel;
    private javax.swing.JPanel Admin_AddStudentPanel;
    private javax.swing.JPanel Admin_DisplayCourseListofStudentPanel;
    private javax.swing.JPanel Admin_DropCoursePanel;
    private javax.swing.JPanel Admin_DropStudentPanel;
    private javax.swing.JTextField CourseDescriptionTextField_AddCourse;
    private javax.swing.JTextField CourseNameTextField_AddCourse;
    private javax.swing.JButton DisplayButton_DisplayCourseListofStudents;
    private javax.swing.JButton DisplayButton_DisplayCourses;
    private javax.swing.JButton DisplayButton_DisplaySchedule;
    private javax.swing.JTable DisplayCoursesTable;
    private javax.swing.JTable DisplayScheduleTable;
    private javax.swing.JButton DropCourseButton_DropCourse_Admin;
    private javax.swing.JComboBox<String> DropCourseComboBox_DropCourse_Admin;
    private javax.swing.JTextArea DropCourseOutputTextArea;
    private javax.swing.JLabel DropCourse_AdminOutputPanel;
    private javax.swing.JButton DropCourse_StudentSubmitButton;
    private javax.swing.JButton DropStudentButton_DropStudent;
    private javax.swing.JTextArea DropStudentOutputTextArea;
    private javax.swing.JTextField FirstNameTextField_AddStudent;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField LastNameTextField_AddStudent;
    private javax.swing.JLabel ScheduleCourseOutput;
    private javax.swing.JButton ScheduleCourseSubmitButton;
    private javax.swing.JTable ScheduledStudentsTable_DisplayButton_DisplayCourseListofStudents;
    private javax.swing.JSpinner SeatsSpinner_AddCourse;
    private javax.swing.JComboBox<String> SelectCourseComboBox;
    private javax.swing.JComboBox<String> SelectCourseComboBox_DisplayCourseListofStudents;
    private javax.swing.JComboBox<String> SelectCourseDropCourse_StudentComboBox;
    private javax.swing.JComboBox<String> SelectStudentComboBox_DropStudent;
    private javax.swing.JTextField StudentIDTextField_AddStudent;
    private javax.swing.JComboBox<String> StudentNameComboBox_DisplaySchedule;
    private javax.swing.JComboBox<String> StudentNameComboBox_DropCourse_Student;
    private javax.swing.JComboBox<String> StudentNameComboBox_ScheduleCourse;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JTabbedPane StudentTab;
    private javax.swing.JPanel Student_DisplayCoursesPanel;
    private javax.swing.JPanel Student_DisplaySchedulePanel;
    private javax.swing.JPanel Student_DropCoursePanel;
    private javax.swing.JPanel Student_ScheduleCoursePanel;
    private javax.swing.JTable WaitlistedStudentsTable_DisplayButton_DisplayCourseListofStudents;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
